baseurl = "https://amanda.rbind.io/"
languageCode = "en-us"
title = "Amanda's Data Blog"
theme = "hugo-lithium"
googleAnalytics = "UA-136228275-1"
#disqusShortname = "amanda-data-blog.disqus.com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/AmandaRP"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/DrAmandaRP"
#[[menu.main]]
#    name = "LinkedIn"
#    url = "https://www.linkedin.com/in/amanda-plunkett-29138399/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "me.jpg"
    width = 50
    height = 50
    alt = "Logo"

