---
title: DC R Conference Recap
author: Amanda
date: '2019-11-12'
slug: dcr
draft: true
categories: []
tags:
  - Conference
---

**The overview**: 

Videos on website in a few weeks.
Slides will also be posted.
`#rstatsdc` hashtag on twitter

Highlights for me included Malorie Hughes' presentation of [`flexdashboard`](#flexdashboard). Somehow in the hype of R [`shiny`](https://shiny.rstudio.com/), I had missed this dashboarding tool. I was also excited to learn about TODO's [`coursedown`](#coursedown) package, which I'm looking forward to testing out for the class that I teach. Another highlight was learning more about the implementation of Google's BERT model in R by TODO.   

**Read more**: Below are my notes from selected talks. I've divided it into the following sections: [Communication](#comms), [modeling](#modeling), [other R packages](#other), [documentation](#doc), [general programming](#programming),. 


## Communication (Dashboards, Websites, and Data Viz) {#comms}

**Coursedown: Managing Course Materials Using R Techniques**
*@webbedfeet*

- Package available [on GitHub](https://github.com/webbedfeet/coursedown).
- Use [`drake`](https://github.com/ropensci/drake) to tie it all together


**Dashboarding Like a Boss**
*Malorie Hughes, Onica (consulting for Amazon)*

- Don’t email your results. Creat a dashboard!
- She demoed [`flexdashboard`](https://rmarkdown.rstudio.com/flexdashboard/) 
- Create using R Markdown. Just requires a different output type in the YAML header.
- See her GitHub repo for templates
- To make your output look pretty on the dashboard:
    - Use [`printr`](https://cran.r-project.org/web/packages/printr/index.html) to make printing R output look better. Less effort than `knitr::kable()`. 
    - Use [`summarytools`](https://cran.r-project.org/web/packages/summarytools/index.html). It's not great YET for R Markdown, but keep tabs on it.
    - For model output, use [`stargazer`](https://cran.r-project.org/web/packages/stargazer/index.html)
    - `DT::datatable()` for interactive table (see advanced options in this function for fancier options for the table)
    - For interactive plots: [`highcharter`](https://cran.r-project.org/web/packages/highcharter/index.html). Assign colors with `colorize()`.
- She included an export/download data button on her dashboard. See her code to learn how to do that. 


**Using networkD3 and R to Visualize and Explore Relationships in Data**
*@DrGates309*
- Talk focused on [`networkD3`](https://cran.r-project.org/web/packages/networkD3/index.html): Nice for interactive networks.
- Other options for visualizing networks: [`igraph`](https://cran.r-project.org › package=igraph), `ggnet2()` (part of [GGally](https://cran.r-project.org/web/packages/GGally/)), and [`visNetwork`](https://cran.r-project.org › package=visNetwork) 
- [`arules`](https://cran.r-project.org › package=arules) package for association mining in R. She used it to find associated words considering both how often words appear together and also how often they appear in same dataset (in her example, how often in the same tweet) 
- [`arulesViz`](https://cran.r-project.org › package=arulesViz) - for visulaization of association rules
- She used the [`igraph`] package to massage the data before giving it to `networkD3`


**Better DataViz in ggplot2: Tips, Tricks, and Examples**
*`@AlexCEngler`*

1. `ggplot2` + [`sf`](https://cran.r-project.org/web/packages/sf/index.html) for bivariate plots: `ggplot2::geom_sf()`. See the [Drawing beautiful maps with R, sf, and ggplot2 sf](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html)  tutorial
2. [`ggtext`](https://github.com/clauswilke/ggtext) to add text to plots using markdown. Includes text formatting. Showed an example of how to highlight parts of title to match highlighted part of graph.
3. [`gghighlight`](https://cran.r-project.org/web/packages/gghighlight/) to highlight parts of graph with color (and grey out rest)
4. `ggplot2::annotation_custom()` to add a plot on top of another (My comment: seems similar to [`cowplot`](https://cran.r-project.org/web/packages/cowplot/index.html)). Creat a "grobe"" and drop it somewhere. Use to zoom in to a map with a bounding box
5. `geofacet::facet_geo()` to create a plot per state, positioned in the location of the states on the map.
6. `ggplot2` extensions: See www.ggplot2-exts.org/gallery and the [`rayshader`](https://cran.r-project.org/web/packages/rayshader/index.html) package.



## Modeling {#modeling}

**RBERT: Cutting Edge NLP in R**
*Jon Harmon, @JonTheGeek*
Slides: bit.ly/jonvsemily

- BERT: **B**idirectional **E**ncoder **R**epresentations from **T**ransformers. Transfer learning for natural language processing. Created by Google. [RBERT](https://github.com/jonathanbratt/RBERT) is the R implementation.
- Older embeddings have one embedding per word. Can’t help this situation: "I saw the branch on the bank."" vs "I saw the branch of the bank."  
- [`RBERTviz`](https://github.com/jonathanbratt/RBERTviz): Visualize attention and PCA. Let’s you see how BERT is thinking. Showed an interactive demo— go watch the video!
- BERT has 12 layers. RBERT usable now (available on GitHub), but the developers are making it more user-friendly. 
- Goal: On CRAN by end of 2019
- Works with tensorflow 2.0 (in testing)
- Example shown: Used RBERT to pull out features for xgboost.


**Optimizing Topic Models for Classification Tasks**
*@thos_jones, IQ-Tel*, PhD research on making topic models better

- Performing research to optimize LDA topic models
- Cousin to LDA: Text embeddings (considered state of the art). In his words, LDA stopped being cared about anymore after deep learning came along. However, he thinks the LDA work was never completed to determine a good LDA model. He thinks LDA might be competitive with deep neural nets if tuned appropriately.
- Walked through an example of classifying 20newsgroups
- Tech stack: textmineR, randomForest (simple so he could focus more on LDA), SigOptR, cloudml, magrittr, stringr, parallel
- SigOpt: ensemble of baysian optimizers for picking hyperparmeters (more efficient than grid search). SigOptR is an R API for SigOpt
Used unigrams, removed stopwords, and wods that were seen in less than 5 docs
- Optimized for accuracy and coherence. LDA was way more accurate than LSA. Showed a accuracy vs topic coherence. 
- He is the maintainer of [`textmineR`](https://cran.r-project.org/web/packages/textmineR/index.html)


**Topic Modeling Consumer Complaints at the Federal Reserve**
*BJ Bloom, @bj_bloom*

- Goal: Use consumer complaints to inform risk analysis for Federal Reserve Board
- Used LDA topic modeling 
- Main LDA packags in R: [lda](https://cran.r-project.org/web/packages/lda/index.html) (old, fine), [`topicmodels`](https://cran.r-project.org/web/packages/topicmodels/index.html) (special snowflake, have to reindex to 0, tricky to use), [`stm`](https://cran.r-project.org/web/packages/stm/index.html) (recommend, structural topic modeling, can use to incorporate metadata into topic model), [`textmineR`](https://cran.r-project.org/web/packages/textmineR/index.html) (recommend, in his opinion includes diagnostic measures that make sense)
- In his words, "Don’t use [`tm`](https://cran.r-project.org/web/packages/tm/index.html). It had its place back in the day." Instead, he's a fan of [`tidytext`](https://cran.r-project.org/web/packages/tidytext/index.html).
- Other R packges used: textrank (for pagerank)


## Spatial Analysis

**The Care and Feeding of Spatial Data**
*Angela Li `@CivicAngela`*

- She described the steps *before* the fancy plots and regression, focusing on the data.
- Two types of spatial data:
    - Vector data - points lines polygons (she focused more on this)
    - Raster data - grids, pixels, cells 
- Geocoding: `tmaptools::geocode_OSM(“Georgetown University”)` gives coordinates (to translate human spatial data to computer understandable spatial data). Note that OSM = "open street map." Talk to your GIS librarian (or if you have ARCGis) to get coords.
- In her words: “Spatial file formats are confusing.”
- Spatial data formats: `.shp` (shapefile made up of 4 files), `.geojson` (lots of web-based mapping), `.gpkg` (new and good, but not common yet), `.csv`, `.tiff` (for raster data)
- Library she uses: [`sf`](https://cran.r-project.org/web/packages/sf/index.html) package. `st_read()` or read_sf() to create a tidy sf dataframe.
- Her tech stack: geoDa, QGIS, ArcGIS, PostGIS, CART, R
- R packages she uses the most (packages in parens are the "comparable" non-spatial versions): [`sf`](https://cran.r-project.org/web/packages/sf/index.html) (readr, tidyr, dplyr), [`tmap`](https://cran.r-project.org/web/packages/tmap/index.html) (ggplot2), [`spdep`](https://cran.r-project.org/web/packages/spdep/index.html) (glmnet), [`sp`](https://cran.r-project.org/web/packages/sp/index.html) (data.table)
- [`rayshader`](https://cran.r-project.org/web/packages/rayshader/index.html) for 3D plotting.  
- Use [`mapview`](https://cran.r-project.org/web/packages/mapview/index.html) for GIS like experience
- Think beyond dots on a map. Are there clusters? Look at spatial autocorrelation and spatially constrained clustering.
- Pre release of [`rgeoda`](https://github.com/lixun910/rgeoda) on GitHub
- See `#rspatial` on Twitter
- Most important slide she’s ever made in her life: 

TODO insert tweet

**R is Not Just Basic Stats: Think Spatially!**
*Tatyana Tsvetovat, `@t_tsvet`*
- Packages she uses: [`rgdal`](https://cran.r-project.org/web/packages/rgdal/index.html), [`rgeos`](https://cran.r-project.org/web/packages/rgeos/index.html), [`sp`](https://cran.r-project.org/web/packages/sp/index.html), [`spatstat`](https://cran.r-project.org/web/packages/spatstat/index.html), [`kernlab`](https://cran.r-project.org/web/packages/kernlab/index.html), [`zoo`](https://cran.r-project.org/web/packages/zoo/index.html)


## General R Programming

**Ten Tremendous Tricks in the Tidyverse**
*David Robinson, @drob*

Be sue to catch his `#tidytuesday` screencasts [on YouTube](https://www.youtube.com/playlist?list=PLEtQC6FY-llkqIhZjI1TYkm4cV6WjobTC). 10 tricks that people have liked from his screencasts:

1. `count(column, sort, wt, name)`: Create a new variable within count. For example: `count(decade = 10 * (year %/% 10)` to produce counts for each decade.
2. `add_count()` adds a count column (really useful to combine with filter to get `x` with a minimum count)
3. Use `summarize()` to create a list column. Looks like `data %>% groupby() %>% summarize`. Example: `summarize(test = list(t.test(avg_score)))` Then use broom to visualize. See [chapter 25 of R for Data Science](https://r4ds.had.co.nz/many-models.html).
3. Use the combination of: `count()`, `fct_reorder()` (to turn column into ordered factor), `geom_col` (use instead of `geom_bar(stat = ‘idendtity’))`, `coord_flip()`,  
`fct_lump()` (to combine least/most common levels together)
4. `scale_x`  or `y_log10()` to use log scale. In his words: “I suspect much more data is log-normal than normal.”
5. `tidyr::crossing()` to find all combinations of multiple vectors. Example: `crossing(a = 1:3, b = A:Z, c = 10:20)`. Can use for simulations in place of for-loops.
5. `separate()` to split a column into multiple columns based on a regex
6. `extract()` to extract information from a column based on a regex
7.
8.
9.
10.



**Raising baby with R**
*Jared lander*

- Jared and his wife recently had a baby. He described his use of R to choose the baby's name and analyze its eating, sleeping, and poo patterns.
- See the [`babynames`](https://cran.r-project.org/web/packages/babynames/index.html) package for data about popularity of baby names
- Analyzing time series data: [`tsibble`](https://cran.r-project.org/web/packages/tsibble/index.html), [`fable`](https://cran.r-project.org/web/packages/fable/index.html), [`feast`](https://cran.r-project.org/web/packages/feasts/index.html).  Use `model()` function in this package to fit `ts` models. Use `autoplot()` to plot `ts` data. `index_by()` is the `ts` equiv of `group_by()`.
- [`fable.prophet`](https://github.com/mitchelloharawild/fable.prophet) package to use prophet in a fable framework. Used this to perform changepoint detection.


**R and Python coexisting in the same Development environment**
*Dan Chen, @chendaniely, Author of “pandas” for everyone*

- What Python does better: environments, web development, and hardware
- What he likes about R: communication (shiny, rmarkdown, ggplot2)
- Python environments in R: 

```{r eval=FALSE}
conda_envs <- reticulate::cond_list()
conda_envs$name[[1]] #have to restart R if you want to change env again)
```

- Most data scientests using Python use anaconda.
- Don’t mix anaconda R package installation with `install.packages()`
- New model pipeline in R: [`rsample`](https://cran.r-project.org/web/packages/rsample/index.html), [`recipes`](https://cran.r-project.org/web/packages/recipes/index.html), [`parsnip`](https://cran.r-project.org/web/packages/parsnip/index.html), [`yardstick`](https://cran.r-project.org/web/packages/yardstick/index.html)   
- Python `joblib` for "pickling" a model in python. Read it into R. Then use R shiny to display 
- [`blogdown`] supports jupyter notebooks
- `knitpy`: `knitr` implementation in python
- Use Apache arrow to pass datasets between R and python
- Information on installing python: 
https://swcarpentry.github.io/python-novice-inflammation/setup/index.html
 



**Managing Your Cloud: Working with APIs**
*Marck Vaisman, Microsoft (Azure team), @wahululu*

- Discussed how to use R to interact with APIs (mostly for the consumption of data)
- [`plumber`](https://cran.r-project.org/web/packages/plumber/index.html) for building and serving up APIs
- three package to be aware of: [`httr`](https://cran.r-project.org/web/packages/httr/index.html) (Part of the tidyverse. More abstract/easier than `curl` package), [`curl`](https://cran.r-project.org/web/packages/curl/index.html) (new package), [`jsonlite`](https://cran.r-project.org/web/packages/jsonlite/index.html) 



## A Few Remaining Random Bits

- Check out the [`memeR`](https://github.com/sctyner/memer) package by `@sctyner`
- R Markdown tips from `@datadanya`: Include `session_info()` at the end of all markdown docs. See https://bootswatch.com/3/ for a list of R Markdown themes
- Use [`gmailr`](https://cran.r-project.org/web/packages/gmailr/index.html) to send email from R
- See [`learnr`](https://cran.r-project.org/web/packages/learnr/index.html) for creating teaching materials. (Use in conjunction with [`gradethis`](https://rstudio-education.github.io/gradethis/.) 
- For conversations about R administration, see `#radmins` on Twitter, solutions.rstudio.com, or the radmins channel on communnity.rstudio.com. Management and IT folks should watch Kelly O’Briant's talk: Reflections on a Year Spent Talking to Data Scientists About DevOps




Idea for a blog post: draw my TODO community (I’d have to pull all of their friends) using D3 — could I post it on my blog?


Geom_tile — heatmap
Sys.setenv(RSTUDIO_R_Version = “”)

TODO
- Import RBERT
- Import coursedown
- Sys.setenv(RSTUDIO_R_Version = “”)
